# Generated by Django 3.0.6 on 2020-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('time_booked', models.DateTimeField(auto_now_add=True)),
                ('loan_start_time', models.DateField()),
                ('loan_end_time', models.DateField()),
            ],
        ),
    ]
