# Generated by Django 3.0.6 on 2020-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_bookeditem_status'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_items',
            field=models.ManyToManyField(to='items.BookedItem'),
        ),
    ]
