# Generated by Django 3.0.6 on 2020-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=('PEN', 'Pending'), max_length=32),
        ),
    ]
