# Generated by Django 3.0.6 on 2020-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('EVA', 'Evaluating'), ('PRO', 'Processed')], default='PEN', max_length=32),
        ),
    ]
