# Generated by Django 3.0.6 on 2020-05-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_deposit_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AddField(
            model_name='booking',
            name='organization',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
