# Generated by Django 3.0.7 on 2020-07-14 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200711_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('EVA', 'Evaluating'), ('PRO', 'Processed'), ('UNC', 'Unconfirmed'), ('GET', 'Retrieved'), ('RET', 'Returned')], default='UNC', max_length=32),
        ),
    ]
