# Generated by Django 3.0.7 on 2020-07-29 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20200715_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(default='00000000', max_length=8, validators=[django.core.validators.RegexValidator('(8[1-8][0-9]{6}|9[0-8][0-9]{6})', 'Invalid phone number.')]),
        ),
    ]
