# Generated by Django 3.0.6 on 2020-05-25 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('brand', models.CharField(default='-', max_length=256)),
                ('remarks', models.TextField(default='-')),
                ('category', models.CharField(default='-', max_length=256)),
                ('deposit', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default=('PEN', 'Pending'), max_length=32)),
                ('booking_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
    ]
