# Generated by Django 3.0.6 on 2020-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200525_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeditem',
            name='status',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('REJ', 'Rejected'), ('PEN', 'Pending')], default='PEN', max_length=32),
        ),
    ]
