# Generated by Django 3.0.7 on 2020-07-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_string', models.CharField(max_length=256)),
                ('template', models.TextField()),
            ],
        ),
    ]
