# Generated by Django 3.0.7 on 2020-07-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmationemails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationemail',
            name='subject',
            field=models.CharField(default='Test', max_length=256),
            preserve_default=False,
        ),
    ]
