# Generated by Django 3.0.7 on 2020-12-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=256)),
                ('email', models.EmailField(default='N/A', max_length=254)),
                ('detail', models.CharField(default='N/A', max_length=3000)),
                ('time_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
