# Generated by Django 3.0.6 on 2020-05-25 06:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=256)),
                ('email', models.EmailField(default='N/A', max_length=254)),
                ('organization', models.CharField(default='N/A', max_length=1000)),
                ('reason', models.TextField(default='-')),
                ('time_booked', models.DateTimeField(auto_now_add=True)),
                ('loan_start_time', models.DateField(default=datetime.date(1970, 1, 1))),
                ('loan_end_time', models.DateField(default=datetime.date(1970, 1, 1))),
                ('deposit_left', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)])),
            ],
        ),
    ]
