# Generated by Django 3.0.7 on 2020-07-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200526_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('EVA', 'Evaluating'), ('PRO', 'Processed'), ('UNC', 'Unconfirmed')], default='UNC', max_length=32),
        ),
    ]
