# Generated by Django 3.0.6 on 2020-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
