# Generated by Django 3.0.6 on 2020-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_bookeditem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='-', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='remarks',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='bookeditem',
            name='status',
            field=models.CharField(default=('PEN', 'Pending'), max_length=32),
        ),
    ]
