# Generated by Django 3.0.6 on 2020-06-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200526_0653'),
        ('items', '0003_auto_20200526_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeditem',
            name='booking_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_items', to='bookings.Booking'),
        ),
    ]
