# Generated by Django 3.0.7 on 2020-07-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200614_0728'),
        ('items', '0004_auto_20200616_0841'),
    ]

    operations = [
    ]
