# Generated by Django 3.0.7 on 2020-07-15 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_merge_20200707_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
    ]
