# Generated by Django 3.0.7 on 2020-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='Default subject', max_length=256),
            preserve_default=False,
        ),
    ]
